// src/video/vulkan_backend.cpp
// SPDX-FileCopyrightText: Copyright 2025 LayraPS4 Emulator Project
// SPDX-License-Identifier: GPL-2.0-or-later
//
// GPU abstraction — translates committed GnmProcessor state into
// real Vulkan draw commands.

#include "vulkan_backend.h"
#include "shader_recompiler.h"
#include <cstdio>
#include <cstring>

namespace Video {

VulkanBackend::VulkanBackend() = default;

VulkanBackend::~VulkanBackend() {
  Shutdown();
}

bool VulkanBackend::Initialize(VkDevice device, VkPhysicalDevice physDevice,
                                VkQueue gfxQueue, u32 queueFamily,
                                VkRenderPass renderPass, VkExtent2D extent) {
  // Validate all required Vulkan handles
  if (device == VK_NULL_HANDLE) {
    fprintf(stderr, "[VulkanBackend] ERROR: VkDevice is VK_NULL_HANDLE\n");
    return false;
  }
  if (physDevice == VK_NULL_HANDLE) {
    fprintf(stderr, "[VulkanBackend] ERROR: VkPhysicalDevice is VK_NULL_HANDLE\n");
    return false;
  }
  if (gfxQueue == VK_NULL_HANDLE) {
    fprintf(stderr, "[VulkanBackend] ERROR: VkQueue is VK_NULL_HANDLE\n");
    return false;
  }
  if (renderPass == VK_NULL_HANDLE) {
    fprintf(stderr, "[VulkanBackend] ERROR: VkRenderPass is VK_NULL_HANDLE\n");
    return false;
  }
  
  device_ = device;
  physDevice_ = physDevice;
  gfxQueue_ = gfxQueue;
  queueFamily_ = queueFamily;
  renderPass_ = renderPass;
  extent_ = extent;

  printf("[VulkanBackend] Initialized (%ux%u)\n", extent_.width, extent_.height);

  // Create the fallback pipeline immediately
  if (!CreateFallbackPipeline()) {
    printf("[VulkanBackend] WARNING: Fallback pipeline creation failed, "
           "draw calls will be skipped\n");
  }

  return true;
}

void VulkanBackend::Shutdown() {
  if (device_ == VK_NULL_HANDLE) return;

  vkDeviceWaitIdle(device_);

  if (fallbackPipeline_ != VK_NULL_HANDLE) {
    vkDestroyPipeline(device_, fallbackPipeline_, nullptr);
    fallbackPipeline_ = VK_NULL_HANDLE;
  }
  if (fallbackLayout_ != VK_NULL_HANDLE) {
    vkDestroyPipelineLayout(device_, fallbackLayout_, nullptr);
    fallbackLayout_ = VK_NULL_HANDLE;
  }

  printf("[VulkanBackend] Shutdown\n");
  device_ = VK_NULL_HANDLE;
}

void VulkanBackend::CommitState(const GuestPipelineState &state) {
  committed_ = state;
  stateValid_ = true;
}

void VulkanBackend::ExecuteDraw(VkCommandBuffer cmd, u32 vertexCount) {
  if (!stateValid_) return;
  
  if (vertexCount == 0) {
    fprintf(stderr, "[VulkanBackend] WARNING: ExecuteDraw called with 0 vertices\n");
    return;
  }

  // If we don't have a command buffer (called from PM4 processing outside
  // a render pass), just track the draw for statistics
  if (cmd == VK_NULL_HANDLE) {
    static u64 drawCount = 0;
    if (drawCount++ % 300 == 0) {
      printf("[VulkanBackend] Draw queued: %u verts, VS=0x%llx, PS=0x%llx "
             "(total: %llu)\n",
             vertexCount,
             (unsigned long long)committed_.vs_program_addr,
             (unsigned long long)committed_.ps_program_addr,
             (unsigned long long)drawCount);
    }
    return;
  }

  // Real draw with a command buffer and our fallback pipeline
  if (fallbackPipeline_ == VK_NULL_HANDLE) {
    fprintf(stderr, "[VulkanBackend] WARNING: Fallback pipeline not created, skipping draw\n");
    return;
  }
  
  vkCmdBindPipeline(cmd, VK_PIPELINE_BIND_POINT_GRAPHICS, fallbackPipeline_);

  VkViewport viewport{};
  viewport.x = static_cast<float>(committed_.viewport_x);
  viewport.y = static_cast<float>(committed_.viewport_y);
  viewport.width = static_cast<float>(committed_.viewport_w);
  viewport.height = static_cast<float>(committed_.viewport_h);
  viewport.minDepth = 0.0f;
  viewport.maxDepth = 1.0f;
  vkCmdSetViewport(cmd, 0, 1, &viewport);

  VkRect2D scissor{};
  scissor.offset = {static_cast<s32>(committed_.viewport_x),
                    static_cast<s32>(committed_.viewport_y)};
  scissor.extent = {committed_.viewport_w, committed_.viewport_h};
  vkCmdSetScissor(cmd, 0, 1, &scissor);

  vkCmdDraw(cmd, vertexCount, 1, 0, 0);
}

void VulkanBackend::ExecuteClear(VkCommandBuffer cmd,
                                  float r, float g, float b, float a) {
  VkClearAttachment clearAtt{};
  clearAtt.aspectMask = VK_IMAGE_ASPECT_COLOR_BIT;
  clearAtt.colorAttachment = 0;
  clearAtt.clearValue.color = {{r, g, b, a}};

  VkClearRect clearRect{};
  clearRect.rect.offset = {0, 0};
  clearRect.rect.extent = extent_;
  clearRect.baseArrayLayer = 0;
  clearRect.layerCount = 1;

  vkCmdClearAttachments(cmd, 1, &clearAtt, 1, &clearRect);
}

// ─── Fallback Pipeline Creation ─────────────────────────────────
// Creates a real Vulkan graphics pipeline using SPIR-V generated by
// our shader recompiler. This draws a fullscreen triangle with the
// Layra blue colour — proves the pipeline works end-to-end.

bool VulkanBackend::CreateFallbackPipeline() {
  if (device_ == VK_NULL_HANDLE || renderPass_ == VK_NULL_HANDLE) {
    fprintf(stderr, "[VulkanBackend] Cannot create pipeline: device=%p, renderPass=%p\n",
            static_cast<void*>(device_), static_cast<void*>(renderPass_));
    return false;
  }

  // Verify extent is valid
  if (extent_.width == 0 || extent_.height == 0) {
    fprintf(stderr, "[VulkanBackend] Invalid render target extent: %ux%u\n",
            extent_.width, extent_.height);
    return false;
  }

  // Generate SPIR-V from our recompiler
  auto vsResult = Shader::LowerToSpirv({}, Shader::ShaderStage::Vertex);
  auto psResult = Shader::LowerToSpirv({}, Shader::ShaderStage::Pixel);

  if (!vsResult.success || !psResult.success) {
    fprintf(stderr, "[VulkanBackend] Shader recompiler failed\n");
    return false;
  }

  // Verify SPIR-V data is not empty
  if (vsResult.spirv.empty() || psResult.spirv.empty()) {
    fprintf(stderr, "[VulkanBackend] Shader recompiler produced empty SPIR-V\n");
    fprintf(stderr, "  VS SPIR-V size: %zu words\n", vsResult.spirv.size());
    fprintf(stderr, "  PS SPIR-V size: %zu words\n", psResult.spirv.size());
    return false;
  }

  // Create shader modules from SPIR-V
  VkShaderModule vsModule = VK_NULL_HANDLE;
  VkShaderModule psModule = VK_NULL_HANDLE;

  VkShaderModuleCreateInfo vsModuleInfo{};
  vsModuleInfo.sType = VK_STRUCTURE_TYPE_SHADER_MODULE_CREATE_INFO;
  vsModuleInfo.codeSize = vsResult.spirv.size() * sizeof(u32);
  vsModuleInfo.pCode = vsResult.spirv.data();

  if (vkCreateShaderModule(device_, &vsModuleInfo, nullptr, &vsModule) !=
      VK_SUCCESS) {
    fprintf(stderr, "[VulkanBackend] Failed to create VS shader module\n");
    return false;
  }

  VkShaderModuleCreateInfo psModuleInfo{};
  psModuleInfo.sType = VK_STRUCTURE_TYPE_SHADER_MODULE_CREATE_INFO;
  psModuleInfo.codeSize = psResult.spirv.size() * sizeof(u32);
  psModuleInfo.pCode = psResult.spirv.data();

  if (vkCreateShaderModule(device_, &psModuleInfo, nullptr, &psModule) !=
      VK_SUCCESS) {
    fprintf(stderr, "[VulkanBackend] Failed to create PS shader module\n");
    vkDestroyShaderModule(device_, vsModule, nullptr);
    return false;
  }

  // Shader stages
  VkPipelineShaderStageCreateInfo shaderStages[2]{};
  shaderStages[0].sType = VK_STRUCTURE_TYPE_PIPELINE_SHADER_STAGE_CREATE_INFO;
  shaderStages[0].stage = VK_SHADER_STAGE_VERTEX_BIT;
  shaderStages[0].module = vsModule;
  shaderStages[0].pName = "main";

  shaderStages[1].sType = VK_STRUCTURE_TYPE_PIPELINE_SHADER_STAGE_CREATE_INFO;
  shaderStages[1].stage = VK_SHADER_STAGE_FRAGMENT_BIT;
  shaderStages[1].module = psModule;
  shaderStages[1].pName = "main";

  // No vertex input — our VS generates vertices procedurally
  VkPipelineVertexInputStateCreateInfo vertexInput{};
  vertexInput.sType = VK_STRUCTURE_TYPE_PIPELINE_VERTEX_INPUT_STATE_CREATE_INFO;

  // Triangle list
  VkPipelineInputAssemblyStateCreateInfo inputAssembly{};
  inputAssembly.sType = VK_STRUCTURE_TYPE_PIPELINE_INPUT_ASSEMBLY_STATE_CREATE_INFO;
  inputAssembly.topology = VK_PRIMITIVE_TOPOLOGY_TRIANGLE_LIST;
  inputAssembly.primitiveRestartEnable = VK_FALSE;

  // Dynamic viewport and scissor
  VkPipelineViewportStateCreateInfo viewportState{};
  viewportState.sType = VK_STRUCTURE_TYPE_PIPELINE_VIEWPORT_STATE_CREATE_INFO;
  viewportState.viewportCount = 1;
  viewportState.scissorCount = 1;

  // Rasterizer
  VkPipelineRasterizationStateCreateInfo rasterizer{};
  rasterizer.sType = VK_STRUCTURE_TYPE_PIPELINE_RASTERIZATION_STATE_CREATE_INFO;
  rasterizer.depthClampEnable = VK_FALSE;
  rasterizer.rasterizerDiscardEnable = VK_FALSE;
  rasterizer.polygonMode = VK_POLYGON_MODE_FILL;
  rasterizer.lineWidth = 1.0f;
  rasterizer.cullMode = VK_CULL_MODE_NONE;
  rasterizer.frontFace = VK_FRONT_FACE_COUNTER_CLOCKWISE;
  rasterizer.depthBiasEnable = VK_FALSE;

  // No multisampling
  VkPipelineMultisampleStateCreateInfo multisampling{};
  multisampling.sType = VK_STRUCTURE_TYPE_PIPELINE_MULTISAMPLE_STATE_CREATE_INFO;
  multisampling.sampleShadingEnable = VK_FALSE;
  multisampling.rasterizationSamples = VK_SAMPLE_COUNT_1_BIT;

  // Colour blending — alpha blend
  VkPipelineColorBlendAttachmentState colorBlendAttachment{};
  colorBlendAttachment.colorWriteMask =
      VK_COLOR_COMPONENT_R_BIT | VK_COLOR_COMPONENT_G_BIT |
      VK_COLOR_COMPONENT_B_BIT | VK_COLOR_COMPONENT_A_BIT;
  colorBlendAttachment.blendEnable = VK_FALSE;

  VkPipelineColorBlendStateCreateInfo colorBlending{};
  colorBlending.sType = VK_STRUCTURE_TYPE_PIPELINE_COLOR_BLEND_STATE_CREATE_INFO;
  colorBlending.logicOpEnable = VK_FALSE;
  colorBlending.attachmentCount = 1;
  colorBlending.pAttachments = &colorBlendAttachment;

  // Dynamic state
  VkDynamicState dynamicStates[] = {VK_DYNAMIC_STATE_VIEWPORT,
                                     VK_DYNAMIC_STATE_SCISSOR};
  VkPipelineDynamicStateCreateInfo dynamicState{};
  dynamicState.sType = VK_STRUCTURE_TYPE_PIPELINE_DYNAMIC_STATE_CREATE_INFO;
  dynamicState.dynamicStateCount = 2;
  dynamicState.pDynamicStates = dynamicStates;

  // Pipeline layout — no descriptors for fallback
  VkPipelineLayoutCreateInfo layoutInfo{};
  layoutInfo.sType = VK_STRUCTURE_TYPE_PIPELINE_LAYOUT_CREATE_INFO;

  if (vkCreatePipelineLayout(device_, &layoutInfo, nullptr, &fallbackLayout_) !=
      VK_SUCCESS) {
    fprintf(stderr, "[VulkanBackend] Failed to create pipeline layout\n");
    vkDestroyShaderModule(device_, vsModule, nullptr);
    vkDestroyShaderModule(device_, psModule, nullptr);
    return false;
  }

  // Create the graphics pipeline
  VkGraphicsPipelineCreateInfo pipelineInfo{};
  pipelineInfo.sType = VK_STRUCTURE_TYPE_GRAPHICS_PIPELINE_CREATE_INFO;
  pipelineInfo.stageCount = 2;
  pipelineInfo.pStages = shaderStages;
  pipelineInfo.pVertexInputState = &vertexInput;
  pipelineInfo.pInputAssemblyState = &inputAssembly;
  pipelineInfo.pViewportState = &viewportState;
  pipelineInfo.pRasterizationState = &rasterizer;
  pipelineInfo.pMultisampleState = &multisampling;
  pipelineInfo.pColorBlendState = &colorBlending;
  pipelineInfo.pDynamicState = &dynamicState;
  pipelineInfo.layout = fallbackLayout_;
  pipelineInfo.renderPass = renderPass_;
  pipelineInfo.subpass = 0;

  VkResult result = vkCreateGraphicsPipelines(device_, VK_NULL_HANDLE, 1,
                                               &pipelineInfo, nullptr,
                                               &fallbackPipeline_);

  // Clean up shader modules — pipeline owns the compiled code now
  vkDestroyShaderModule(device_, vsModule, nullptr);
  vkDestroyShaderModule(device_, psModule, nullptr);

  if (result != VK_SUCCESS) {
    fprintf(stderr, "[VulkanBackend] Failed to create graphics pipeline "
                    "(VkResult=%d)\n", result);
    return false;
  }

  printf("[VulkanBackend] Fallback pipeline created successfully\n");
  return true;
}

} // namespace Video
